services:
    notebook:
        container_name: notebook
        build: 
            context: .
        ports:
            - "58002:8888"
        volumes:
            - ./Notebooks:/Notebooks
        command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/Notebooks"
        environment:
            - IRISINSTALLDIR='/usr/irissys'